workflows:
  ios-simulator-workflow:
    name: iOS Simulator Build for Appetize.io
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Build x86_64 iOS Simulator App
        script: |
          flutter build ios --simulator --no-codesign
          xcodebuild -workspace ios/Runner.xcworkspace -scheme Runner -configuration Debug -sdk iphonesimulator -arch x86_64 ONLY_ACTIVE_ARCH=NO build
      - name: Zip Simulator App
        script: |
          cd build/ios/iphonesimulator
          zip -r Runner.app.zip Runner.app
    artifacts:
      - build/ios/iphonesimulator/Runner.app.zip
