server {
    listen 80;
    server_name web.baknuschat.smkbn666.sch.id localhost _ ;

    root /usr/share/nginx/html;
    index index.html;

    include /etc/nginx/mime.types;
    types {
        application/wasm wasm;
        application/javascript js;
    }

    # Gzip Compression untuk performa loading cepat
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript image/svg+xml application/wasm;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Cache statis untuk aset Flutter
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|ttf|woff|woff2|wasm|json)$ {
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }

    # Penanganan error page
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
